<?php
// add custom post type business to the activity stream
add_filter ( 'bp_blogs_record_post_post_types', 'activity_publish_custom_post_types',1,1 );
function activity_publish_custom_post_types( $post_types ) {
$post_types[] = 'video';
return $post_types;
}

add_filter('bp_blogs_activity_new_post_action', 'record_cpt_activity_action', 1, 3);
function record_cpt_activity_action( $activity_action, $post, $post_permalink ) {
global $bp;
if( $post->post_type == 'video' ) {

$activity_action = sprintf( __( '%1$s added the video %2$s to the <a href="http://videos.cfcommunity.net">CF Video Library</a>', 'buddypress' ), bp_core_get_userlink( (int)$post->post_author ), '<a href="' . $post_permalink . '">' . $post->post_title . '</a>', get_blog_option($blog_id, 'blogname') );

}
return $activity_action;
}

add_action( 'template_redirect', 'bpdev_wpseo_title_fix_for_bp' );
/**
 * Remove WP Seo plugin hooks that changes titles
 * @global type $wpseo_front
 * @return type
 */
function bpdev_wpseo_title_fix_for_bp(){
 
 if( ! function_exists( 'initialize_wpseo_front' ) )
 return;
 
 if( bp_is_blog_page() )
 return;
 
 //we will remove the title generation by wp seao and the title generated by BuddyPress will be used automatically
 
 global $wpseo_front;
 
 //remove the title generator
 remove_filter('wp_title', array($wpseo_front,'title'),15, 3 );
 
 if( has_action( 'wp_footer', array( $wpseo_front, 'flush_cache' ) ) )
 remove_action( 'wp_footer', array( $wpseo_front, 'flush_cache' ) );
 
}
/**
 * Get current page url without query string
 * based on http://webcheatsheet.com/PHP/get_current_page_url.php
 * modified to exclude the query string
 *
 * @return string url
 */
 
function bpdev_get_current_url() {
 
 $page_url = 'http';
 
 if ( isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' )
  $page_url .= 's';
 
  //append //
 
  $page_url .= '://';
 
 if ($_SERVER['SERVER_PORT'] != '80')
  $page_url .= $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'].$_SERVER['REQUEST_URI'];
 else
  $page_url .= $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
 
 //find if the url has query variables
 $query_pos = strpos( $page_url, '?' );
 
 //let us exclude that section from url
 if( $query_pos )
 $page_url = substr( $page_url, 0, $query_pos );
 
 return $page_url;
}
add_filter( 'wpseo_canonical','bpdev_fix_cannonical_url_for_bp' );
function bpdev_fix_cannonical_url_for_bp($url){
 
 if( bp_is_blog_page() || bp_is_directory() )
 return $url;
 
 //in other case, return current url without the query string
 
 $url = bpdev_get_current_url();//
 //$url = add_query_arg(array( 'foo'=>false ) );//, get_home_url());
 return $url;
 
}
//generate meta description
add_filter( 'wpseo_metadesc', 'bpdev_bp_items_metadesc' );
 
function bpdev_bp_items_metadesc( $desc ){
 // if it is not buddypress page or buddypress directory pages let the plugin do its work
 
 if( bp_is_blog_page() || bp_is_directory() )
 return $desc;
 //we do not cover directory as directory meta can be customized from pages->Edit screen
 
 //now, let us check if we are on members page
 
 if( bp_is_user() ){
 
 //what should me the description, I am going to put it like Profile & Recent activities of [user_dsplay_name] on the site [sitename]
 //if you are creative, you can use some xprofile field and xprofile_get_field_data to make it better
 $desc = sprintf('%s\'s Profile & Recent activities on %s ', bp_get_displayed_user_fullname(), get_bloginfo( 'name' ) );
 
 //here we can do it based on each of the component or action using bp_si_current_component(;'component name') && bp_is_current_action('action_name')
 
 //here I am showing an example for BuddyBlog component
 //on buddyblog single post
 if(function_exists( 'buddyblog_is_single_post') && buddyblog_is_single_post() ){
 
 //get the post id
 //
 //buddyblog currently does not have api to get single post, I will add that in next version, for now, We will do the chore ourself
 
 $post_id = 0;
 //make sure
 //check the strategy
 if( buddyblog_use_slug_in_permalink() ){
 $slug = bp_action_variable(0);
 $post_id = buddyblog_get_post_id_from_slug( $slug );
 
 }else{
 $post_id = intval( bp_action_variable(0) );
 
}
 
 if( $post_id ){
 
 $desc = wpseo_get_value( 'metadesc', $post_id );
 
 //let us update description
 }
 
 }
 
 //I have another strategy that I will propose at the end of this post to make it super easy
 
 } elseif( bp_is_active( 'groups' ) && bp_is_group() ){//for single group
 //let us use group description
 $post_id = false;
 //by default, use group description
 $group = groups_get_current_group();
 $desc = $group->description;
 //are we looking for forum?
 
 if( bp_is_current_action( 'forum' ) && function_exists( 'bbpress' ) ){
 
 $forum_ids = bbp_get_group_forum_ids ();//we will get an array of ids
 
 if( $forum_ids )
 $post_id = array_pop ($forum_ids);
 
 //check if we are at single topic
 if( bp_is_action_variable('topic', 0) && bp_action_variable(1) ){
 //we are on single topic, get topic id
 //get the topic as post
 $topics = get_posts(array('name'=>bp_action_variable(1), 'post_type'=> bbp_get_topic_post_type(), 'per_page'=>1));
 //get the id
 if( !empty( $topics ) )
 $post_id = $topics[0]->ID;
 }
 } //end of forum post finding
 //if the post id is given
 if( $post_id ){
 
 $desc = wpseo_get_value( 'metadesc', $post_id );
 
 //let us update description
 }
 //check if the forum is active and get the current post id /meta
 
 }//end of group section
 //do it for other components
 //ok, so you can go and do the same for all the other pages
 //finally return the description
 return $desc;
 
}
?>